"""Print the real capability surface from code. Writes Docs/internal/CAPABILITY-INVENTORY.md."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


def main() -> int:
    from nexus.app import _count_tools, create_server
    from nexus.cli.main import app as cli
    from nexus.ingest.registry import get_registry
    from nexus.tools.windows import _WIN_CATALOG

    server = create_server()
    mcp_names = sorted(server._tool_manager._tools.keys())
    mcp_n = _count_tools(server)

    cli_cmds: list[str] = []
    for cmd in cli.registered_commands:
        name = cmd.name or getattr(cmd.callback, "__name__", "?")
        cli_cmds.append(name)
    for group in cli.registered_groups:
        gname = group.name or "?"
        cli_cmds.append(gname)
        inner = group.typer_instance
        if inner is None:
            continue
        for sub in inner.registered_commands:
            sname = sub.name or getattr(sub.callback, "__name__", "?")
            cli_cmds.append(f"{gname} {sname}")
    cli_cmds = sorted(set(cli_cmds))

    reg = get_registry()
    sources = sorted(s.value for s in reg.all_sources())
    classes: list[str] = []
    for src in reg.all_sources():
        for cls in reg.candidates(src):
            classes.append(f"{cls.__name__} ({src.value})")

    win_bins = [f"{k} → {v['name']} [{v['category']}]" for k, v in sorted(_WIN_CATALOG.items())]

    catalog_dir = ROOT / "src" / "nexus" / "data" / "catalog"
    sift_bins: list[str] = []
    if catalog_dir.is_dir():
        import yaml
        for yml in sorted(catalog_dir.glob("*.yaml")) + sorted(catalog_dir.glob("*.yml")):
            data = yaml.safe_load(yml.read_text(encoding="utf-8")) or {}
            if isinstance(data, dict):
                for item in data.get("tools") or data.get("binaries") or []:
                    if isinstance(item, dict) and item.get("name"):
                        sift_bins.append(str(item["name"]))
                    elif isinstance(item, str):
                        sift_bins.append(item)

    out = ROOT / "Docs" / "internal" / "CAPABILITY-INVENTORY.md"
    lines = [
        "# CAPABILITY-INVENTORY (generated — do not hand-edit counts)",
        "",
        f"Generated by `scripts/list-capabilities.py` on {sys.platform}.",
        "",
        f"- MCP tools this host: **{mcp_n}**",
        f"- CLI top-level / groups: **{len(cli_cmds)}**",
        f"- Importer sources: **{len(sources)}**",
        f"- Importer classes: **{len(classes)}**",
        f"- Windows catalog: **{len(_WIN_CATALOG)}**",
        f"- SIFT yaml names found: **{len(sift_bins)}**",
        "",
        "## MCP tools",
        "",
        *[f"- `{n}`" for n in mcp_names],
        "",
        "## CLI",
        "",
        *[f"- `{n}`" for n in cli_cmds],
        "",
        "## Importer sources",
        "",
        *[f"- `{s}`" for s in sources],
        "",
        "## Importer classes",
        "",
        *[f"- `{c}`" for c in classes],
        "",
        "## Windows catalog",
        "",
        *[f"- `{b}`" for b in win_bins],
        "",
        "## SIFT catalog names (yaml)",
        "",
        *([f"- `{b}`" for b in sift_bins] or ["- (none parsed)"]),
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")
    print(f"mcp={mcp_n} cli={len(cli_cmds)} sources={len(sources)} classes={len(classes)} win={len(_WIN_CATALOG)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
